#!/usr/bin/with-contenv bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
if [ "${OTBR_WEB:-1}" != "0" ]; then
    echo "INFO: Starting otbr-web..."
    declare otbr_web_port

    otbr_web_port="${OTBR_WEB_PORT:-8080}"

    exec stdbuf -oL /usr/sbin/otbr-web -I wpan0 -d6 -s -p "${otbr_web_port}"
else
    echo "INFO: Skipping otbr-web, disabled..."
    exec s6-pause
fi
